services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promise_dev
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

  promise:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - ${APP_PORT:-4000}:4000
    restart: unless-stopped


volumes:
  postgres:
