services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-promise_prod}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    restart: unless-stopped
  
  app:
    build:
      context: .
    depends_on:
      - database
    # ports:
    #   - ${APP_PORT:-4000}:4000
    environment:
      PHX_HOST: ${PHX_HOST:-localhost}
      DATABASE_URL: ${DATABASE_URL:-ecto://postgres:postgres@database/promise_prod}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    restart: unless-stopped
  
  swagger:
    image: swaggerapi/swagger-ui
    # ports:
    #   - ${SWAGGERUI_PORT:-4001}:8080
    environment:
      API_URL: http://${PHX_HOST:-localhost}:${HTTP_PORT:-80}/openapi.yml
      BASE_URL: ${BASE_URL:-/docs}
    restart: unless-stopped

  nginx:
    depends_on:
      - app
      - swagger
    image: nginx:latest
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    
