services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promise_dev
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGERUI_PORT:-4001}:8080
    volumes:
      - ./priv/static/openapi.yml:/usr/share/nginx/html/doc/openapi.yml:ro
    environment:
      API_URL: doc/openapi.yml
    restart: unless-stopped

volumes:
  postgres:
  pgadmin-data:
